# Site settings
title: Starter
email: info@trim.media
description: > # this means to ignore newlines until "baseurl:"
  Starter helps startups get professional design services for their business.
baseurl: ""
url: "http://starter.design"

# Build settings
markdown: kramdown
